[package]
name = "daemonbase"
authors = ["NLnet Labs <rust-team@nlnetlabs.nl>"]
description = "A library for providing the foundation for daemon processes."

version = "0.1.4"
edition = "2024"
rust-version = "1.87"

documentation = "https://docs.rs/daemonbase/"
homepage = "https://github.com/nlnetlabs/daemonbase/"
repository = "https://github.com/NLnetLabs/daemonbase^"
keywords = ["daemon", "logging", "system-service" ]
categories = ["config"]
license = "BSD-3-Clause"

[dependencies]
clap            = { version = "4.5.51", features = [ "derive" ] }
jiff            = { version = "0.2.15" }
log             = "0.4.8"
serde           = { version = "1.0.228", features = [ "derive" ] }
tokio           = { version = "1.40", features = [ "macros", "signal" ], optional = true }
toml_edit       = "0.25.11"


[target.'cfg(unix)'.dependencies]
nix             = { version = "0.31", features = [ "fs", "net", "process", "socket", "user" ] }
syslog          = "7"
time            = "0.3.9" # used by 'syslog'

